(function () {
	const Game_Map_setup = Game_Map.prototype.setup;
	Game_Map.prototype.setup = function (mapId) {
		Game_Map_setup.call(this, mapId);

		var ary = [
			10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 34, 35, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
			54, 55, 56, 72, 73, 76, 77, 81, 82, 83
		];
		this._CBR_ninsin_flag = ary.includes(mapId);
	};

	Game_Map.prototype.CBR_ninsin_flag = function () {
		return this._CBR_ninsin_flag;
	};

	const Game_Party_increaseSteps = Game_Party.prototype.increaseSteps;
	Game_Party.prototype.increaseSteps = function () {
		Game_Party_increaseSteps.call(this);

		//妊娠イベントを起こすマップの定義
		if ($gameMap.CBR_ninsin_flag()) {
			//白雪操作時
			if ($gameSwitches.value(117)) {
				if ($gameVariables.value(182) > 0) {
					$gameVariables.setValue(186, $gameVariables.value(186) - 1);
					if ($gameVariables.value(186) <= 0) {
						$gameSwitches.setValue(131, true);
					}
				}
				//夜鶴操作時
			} else {
				if ($gameVariables.value(183) > 0) {
					$gameVariables.setValue(187, $gameVariables.value(187) - 1);
					if ($gameVariables.value(187) <= 0) {
						$gameSwitches.setValue(131, true);
					}
				}
			}
		}
	};
})();
